# Generated by Django 3.0.7 on 2020-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email_Phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
